import { Activity, AlertCircle, Clock, Cpu, HardDrive, Network, Server, Webhook } from "lucide-react";

export  const servers = [
    {
      id: "SRV-001",
      name: "ERP-PROD",
      status: "online",
      uptime: 99.8,
      cpu: 45,
      memory: 67,
      storage: 34,
      latency: 12,
      packetLoss: 0.1,
      apiResponseTime: 250,
      activeUsers: 150,
      webhookEvents: 320,
      location: "Data Center Principal",
      lastCheck: "30s atrás",
      type: "Servidor de Produção",
      connectionTypes: ["ping", "snmp", "api", "webhook"],
    },
    {
      id: "SRV-002",
      name: "WEB-SERVER-01",
      status: "online",
      uptime: 99.9,
      cpu: 23,
      memory: 45,
      storage: 56,
      latency: 8,
      packetLoss: 0.05,
      apiResponseTime: 180,
      activeUsers: 200,
      webhookEvents: 500,
      location: "Data Center Principal",
      lastCheck: "15s atrás",
      type: "Servidor Web",
      connectionTypes: ["ping", "snmp", "api"],
    },
    {
      id: "SRV-003",
      name: "DB-CLUSTER",
      status: "warning",
      uptime: 98.5,
      cpu: 78,
      memory: 84,
      storage: 67,
      latency: 15,
      packetLoss: 0.3,
      apiResponseTime: 300,
      activeUsers: 80,
      webhookEvents: 100,
      location: "Data Center Secundário",
      lastCheck: "45s atrás",
      type: "Cluster de Base de Dados",
      connectionTypes: ["ping", "snmp"],
    },
    {
      id: "SRV-004",
      name: "BACKUP-SRV",
      status: "offline",
      uptime: 95.2,
      cpu: 0,
      memory: 0,
      storage: 89,
      latency: 0,
      packetLoss: 100,
      apiResponseTime: 0,
      activeUsers: 0,
      webhookEvents: 0,
      location: "Data Center Backup",
      lastCheck: "5m atrás",
      type: "Servidor de Backup",
      connectionTypes: ["ping"],
    },
  ];

export const connectionTypes = [
     {
       type: "ping",
       label: "Ping",
       icon: Clock,
       metrics: [
         { label: "Latência",
            key: "latency", 
            unit: "ms", 
            description: "Tempo de resposta da rede em milissegundos", 
            icon: Clock },
         { label: "Perda de Pacotes", 
            key: "packetLoss",
             unit: "%", 
            description: "Porcentagem de pacotes perdidos durante a comunicação", 
            icon: AlertCircle },
       ],
     },
     {
       type: "snmp",
       label: "SNMP",
       icon: Network,
       metrics: [
         { label: "CPU",
            key: "cpu", 
            unit: "%", 
            description: "Uso percentual da CPU do equipamento", 
            icon: Cpu },
         { label: "Memória",
            key: "memory", 
            unit: "%", 
            description: "Uso percentual da memória RAM",
             icon: Activity },
         { label: "Disco",
             key: "storage", 
             unit: "%",
              description: "Uso percentual do armazenamento", 
              icon: HardDrive },
       ],
     },
     {
       type: "api",
       label: "API",
       icon: Server,
       metrics: [
         { label: "Tempo de Resposta",
             key: "apiResponseTime",
            unit: "ms", description: "Tempo médio de resposta das requisições API",
             icon: Clock,
         },
         { label: "Usuários Ativos",
            key: "activeUsers",
             unit: "", 
             description: "Número de usuários ativos na aplicação",
              icon: Activity, },
       ],
     },
     {
       type: "webhook",
       label: "Webhook",
       icon: Webhook,
       metrics: [
         { label: "Eventos Recebidos",
            key: "webhookEvents",
            unit: "",
            description: "Quantidade de eventos recebidos via webhook",
            icon: Webhook
         },
       ],
     },
   ];